server:
  port: 10001
  context-path: /user
spring:
  application:
    name: user-center
  profiles:
    active: dev
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/registry/eureka
