server:
  port: 10003
  context-path: /house
spring:
  application:
    name: service-house
  profiles:
    active: dev
#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin:admin@localhost:9000/registry/eureka/
